{% set data = load_setup_py_data() %}

package:
  name: pycrop2ml_ui
  version: {{ data.get('version') }}

source:
  path: ..

build:
  noarch: python  
  preserve_egg_dir: True
  number: 0
  script: {{PYTHON}} setup.py install 

requirements:
  build:
    - python {{PY_VER}}
    - setuptools
  run:
    - python {{PY_VER}}
    - pycropml
    - wheel
    - qgrid  ==1.3.1
    - pandas
    - cookiecutter
    - ipywidgets <8
    - ipyfilechooser ==0.4.4
    - matplotlib-base
    - urllib3
    - jupyterlab ==2.3.2
    - requests



#test:
#  imports:
#    - pycrop2ml_ui

about:
  home: https://github.com/AgriculturalModelExchangeInitiative/Pycrop2ml_ui
  license: Cecill-c License
  summary: Jupyter interface to PyCrop2ML 

